import type { Metadata } from "next";
import { Navbar } from "../components/navbar";
import { Footer } from "../components/footer";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Swing Path",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
